### ISSUE TITLE
Are the options lines duplicated on purpose?

### ISSUE THREAD

**Issue by beebe4** [q9f/omniauth-ethereum.rb#10]
https://github.com/q9f/omniauth-ethereum.rb/blob/6084668ba77f1898da0296d1978f45707ca1a983/lib/omniauth-ethereum.rb#L17

If so, why do they need to be duplicated?

**Comment by q9f** [comment]
No, that must be a merge relict.

This gem is in a very early stage. If you wish to review/test/improve it, I’m happy to give you some access.

I’m currently focussed on rewriting the eth gem but might get back to this one soon.
