### ISSUE TITLE
Strategy fails if `custom_title` in configuration contains numbers

### ISSUE THREAD

**Issue by kirushik** [q9f/omniauth-ethereum.rb#21]
In https://github.com/q9f/omniauth-ethereum.rb/blob/db34570f4ec7b6ab8ca1358b762c3a1435eb6f04/lib/new_session.js#L27 the message to be signed is specified as concatenated `customTitle` and `requestTime`.

Though, in https://github.com/q9f/omniauth-ethereum.rb/blob/db34570f4ec7b6ab8ca1358b762c3a1435eb6f04/lib/omniauth-ethereum.rb#L46 `unix_time` is extracted using `message.scan(/\d+/).first.to_i`.

Therefore, if one's customTitle contains any numbers (like in, say, "SuperFrobinator 2024") the authentication fails.

It seems that simply replacing `first` with `last` when parsing `message` would be enough to fix this bug.

**Comment by q9f** [comment]
It's not very elegant admittedly but happy to hotfix it to `last` as I don't see any obvious side effects currently.
