### ISSUE TITLE
2 issues while trying to use

### ISSUE THREAD

**Issue by beebe4** [q9f/omniauth-ethereum.rb#5]
1. have to include `branch: main` (good on you) was getting:
```
❯ bundle
Fetching https://github.com/q9f/omniauth-ethereum.git
fatal: Needed a single revision
Git error: command `git rev-parse --verify master` in directory
/Users/project/core has failed.
Revision master does not exist in the repository
https://github.com/q9f/omniauth-ethereum.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory
'/Users/beebe4/.rvm/gems/ruby-2.7.2/cache/bundler/git/omniauth-ethereum-2fd54d8c03f57fcb075461c8088506557d671a3f'
```
So added:
```
`gem 'omniauth-ethereum', :github => 'q9f/omniauth-ethereum', branch: 'main'`
```
2. Now getting this:
```
❯ bundle
Fetching https://github.com/q9f/omniauth-ethereum.git
WARNING: /Users/beebe4/.rvm/rubies/ruby-2.7.2/bin/ruby is loading libcrypto in an unsafe way
[1]    43323 abort      bundle
```

**Comment by q9f** [comment]
> WARNING: /Users/beebe4/.rvm/rubies/ruby-2.7.2/bin/ruby is loading libcrypto in an unsafe way

I'm sorry. This is a macos issue with the `eth` gem that I coudln't fix yet. https://github.com/se3000/ruby-eth/pull/66

I don't have a mac, so I'm of limited help here.

**Comment by q9f** [comment]
> have to include `branch: main` (good on you) was getting:

You can use ruby gems now: https://rubygems.org./gems/omniauth-ethereum, I just pushed it. I'm still testing it myself though.

**Comment by justinsoong** [comment]
@beebe4 I had that issue, and I did some symlinking to temporarily resolve it, find your libssl library, then link see the thread in se3000/ruby-eth#66
